### ISSUE TITLE
Create symbol for Ground

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/schematic-symbols#171]
![Image](https://github.com/user-attachments/assets/41641fae-360c-4621-bb0b-259dce69ab6d)

**Comment by TSP06** [comment]
@imrishabh18 I want to work on this please assign me this .

**Comment by TSP06** [comment]
And also can you please label the issue Hacktoberfest

**Comment by imrishabh18** [comment]
This repo has been labelled hacktoberfest. So, it will be counted towards it

**Comment by TSP06** [comment]
[![Image](https://github.com/user-attachments/assets/d3d8cd1c-0ee6-4a7b-beb2-61923f34889f)
i have created the symbol but running bun run test 1 test is getting failed for ground_horz due to unmatched svg

**Comment by TSP06** [comment]
@seveibar please help with this issue despite creating correct symbols bun run test is getting failed

**Comment by seveibar** [comment]
@TSP06 you probably need to `export BUN_UPDATE_SNAPSHOTS=1 bun test <path/to/test/file.test.ts>`

You can also delete the original snapshot.
