### ISSUE TITLE
bun start not working, I think  wrong import format on windows

### ISSUE THREAD

**Issue by Abse2001** [tscircuit/schematic-symbols#18]
![image](https://github.com/user-attachments/assets/c25d445d-f5f8-4b75-afdc-4b01c0e1b038)

**Comment by seveibar** [comment]
CC @imrishabh18

**Comment by seveibar** [comment]
i think this is an issue with [make-vfs](https://github.com/seveibar/make-vfs), it should use `import path from "path/posix"` instead of `import path from "path"` to be windows compatible. @Abse2001 would you like to take a stab at fixing it?

**Comment by imrishabh18** [comment]
Taking a look

**Comment by imrishabh18** [comment]
@Abse2001 Pull the latest main and let me know if it works

**Comment by Abse2001** [comment]
Ok

**Comment by Abse2001** [comment]
@imrishabh18  still the same problem
![image](https://github.com/user-attachments/assets/4ba3b13c-99e4-4a90-b48a-765e775398b2)

**Comment by imrishabh18** [comment]
This seems weird, it should have not happened. Cause this file was not changed

**Comment by imrishabh18** [comment]
Probably can you `git stash` your changes, and then checkout to the latest main and share what you see in this file?
