### ISSUE TITLE
Diode component should have `up`, `down`, `left` and `right` variants

### ISSUE THREAD

**Issue by seveibar** [tscircuit/schematic-symbols#189]
Look at diode symbol at https://symbols.tscircuit.com/

It should have a left/right/up/down variants instead of horz/vert

A utility function should be created and used to minimize effort when converting future symbols

/bounty $40

**Comment by aybanda** [comment]
Hi @seveibar,

I wanted to follow up on the diode variants discussed in this issue. I have implemented the following transformations based on the intended orientations:

I have created a utility function (i.e generateDiodeVarients.ts in utils directory) to generate diode_up.svg , diode_right, diode_left, diode_down in assets/symbols

Could you please confirm if these transformations align with your expectations for the diode orientations? I want to ensure that the implementation meets the project's requirements.
