### ISSUE TITLE
Create the crystal oscillator symbol

### ISSUE THREAD

**Issue by imrishabh18** [tscircuit/schematic-symbols#200]
![Image](https://github.com/user-attachments/assets/8e9e0f22-cc48-4c9f-8902-9c9d520f9209)

**Comment by kom-senapati** [comment]
/attempt #200

Creating svg and following steps as stated

**Comment by seveibar** [comment]
@imrishabh18 it already exists...

![Image](https://github.com/user-attachments/assets/e9effc92-4311-4f60-a0d5-b5ef4e437e4f)
