### ISSUE TITLE
Create symbol for npn_bipolar_transistor

### ISSUE THREAD

**Issue by seveibar** [tscircuit/schematic-symbols#39]

**Comment by programmersoham** [comment]
Hey, there are two NPN bipolar transistors possible. Should I put both of them for this issue? 
![Image](https://github.com/user-attachments/assets/4a9030ab-184a-44cb-8024-2462a5a47903)

**Comment by programmersoham** [comment]
Please close this issue as the PR is merged

**Comment by Timer00** [comment]
#107 has added the SVG for this issue but we still need to create the .ts files for rendering it.

**Comment by mrudulpatil18** [comment]
working on this
