### ISSUE TITLE
Adding issue and PR templates

### ISSUE THREAD

**Issue by Sibam-Paul** [tscircuit/schematic-symbols#79]
Will add bug ,docs, feat for issue templates
and PR templates

@tscircuitbot  **Please assign me this issue under hacktoberfest wanna work on it**

**Comment by seveibar** [comment]
@Sibam-Paul for the sake of avoiding spam, we're only going to allow issue template PRs for people who are repeat contributors on a repo

**Comment by Sibam-Paul** [comment]
@seveibar Why will it be a spam didn't get it ???

**Comment by seveibar** [comment]
Only people who create a lot of good issues or solve a lot will create the best issue template for a repo. Generic issue templates aren't very helpful, a good issue template should be specific to the repo and make it easier for contributors and issue creators

**Comment by Sibam-Paul** [comment]
@seveibar Got it bro thanks for explaining
